name: Deploy dev meetup

on:
  push:
    branches:
      - dev

env:
  SOURCE_DIR: "portfolio/dist"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd portfolio && npm install

      - name: Build dist
        run: cd portfolio && npm run build

      - name: Check if build folder exists
        run: ls -al portfolio/dist

      - name: Configure Git
        run: |
          git config --global user.name "Rebecka Larsson"
          git config --global user.email "rebeckaelin@example.com"

      - name: Checkout gh-pages branch or create orphan if not exists
        run: |
          git fetch --all
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages  # Skapar en "orphan" gh-pages branch om den inte finns
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: portfolio/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
